mybatis:
  mapper-locations: classpath*:mappers/**/**Dao.xml


spring:
  datasource:
    url: jdbc:mysql://120.79.155.125:3396/social-system?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver