spring:
  profiles:
    active: matebook

  datasource:
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.github.mrag.wechat.type

logging:
  level:
    com.github.mrag.wechat: debug

server:
  port: 4200
  servlet:
    context-path: /api
