server:
  port: 4399
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: java:mysql://120.79.155.125:3306/db_presevere_new?serverTimezone=Asia\Shanghai&useSSL=false
      username: root
      password: root

mybatis:
  type-aliases-package: cn.gmwenterprise.presevere.domain
  mapper-locations: classpath:/mapping/