spring:
  application:
    name: springboot-dubbo-demo
dubbo:
  application:
    name: springboot-provider # 提供方应用信息，用于计算依赖关系
  protocol:
    name: dubbo # 作为提供方的协议信息，默认dubbo，可选有hessian、webservice等等
    port: 20880 # 提供方端口号
    host: 127.0.0.1
  registry:
    address: N/A # N/A表示不使用注册中心，依靠点对点接受服务