spring:
  datasource:
    url: jdbc:mysql://120.79.155.125:3396/product-msg-qrcode?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#  thymeleaf:
#    cache: false
#    encoding: UTF-8
#    mode: HTML
#    servlet:
#      content-type: text/html
#    prefix: classpath:/templates/
#    suffix: .html
