rpc:
  port: 8888
  default-serial: json

server:
  port: 4200
  servlet:
    context-path: /rpc

management:
  endpoints:
    web:
      exposure:
        include: health, info, shutdown
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: true