package cn.gmwenterprise.presevere.dao;

import cn.gmwenterprise.presevere.domain.ArticleTagStore;
import cn.gmwenterprise.presevere.vo.TagCountVo;

import java.util.List;

public interface ArticleTagStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_store
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_store
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    int insert(ArticleTagStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_store
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    int insertSelective(ArticleTagStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_store
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    ArticleTagStore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_store
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleTagStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_store
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    int updateByPrimaryKey(ArticleTagStore record);

    int deleteByUrlNumber(Long urlNumber);

    int insertBatch(List<ArticleTagStore> tagStores);

    List<TagCountVo> groupByTag();
}