package cn.gmwenterprise.presevere.dao;

import cn.gmwenterprise.presevere.domain.ArticleDraft;

public interface ArticleDraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_draft
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_draft
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int insert(ArticleDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_draft
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int insertSelective(ArticleDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_draft
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    ArticleDraft selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_draft
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_draft
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ArticleDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_draft
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int updateByPrimaryKey(ArticleDraft record);
}