package cn.gmwenterprise.presevere.dao;

import cn.gmwenterprise.presevere.domain.ArticleMetadata;

public interface ArticleMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_metadata
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_metadata
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int insert(ArticleMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_metadata
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int insertSelective(ArticleMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_metadata
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    ArticleMetadata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_metadata
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_metadata
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int updateByPrimaryKey(ArticleMetadata record);

    ArticleMetadata selectByUrlNumber(Long urlNumber);

    int updateByUrlNumber(ArticleMetadata metadata);
}