package cn.gmwenterprise.presevere.dao;

import cn.gmwenterprise.presevere.domain.SysUser;

import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    SysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    int updateByPrimaryKey(SysUser record);

    SysUser selectByUsername(String username);

    int countByUsername(String username);

    List<SysUser> selectByCondition(SysUser condition);

    int countByUserId(Integer userId);

    int countByFullNickname(Integer userId, String nickname);

    int countByPhone(Integer userId, String phone);

    int countByEmail(Integer userId, String email);
}