package cn.gmwenterprise.presevere.domain;

public class ArticleBodyWithBLOBs extends ArticleBody {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_body.content
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_body.content_plain
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    private String contentPlain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_body.content_md
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    private String contentMd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_body.content
     *
     * @return the value of article_body.content
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_body.content
     *
     * @param content the value for article_body.content
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_body.content_plain
     *
     * @return the value of article_body.content_plain
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    public String getContentPlain() {
        return contentPlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_body.content_plain
     *
     * @param contentPlain the value for article_body.content_plain
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    public void setContentPlain(String contentPlain) {
        this.contentPlain = contentPlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_body.content_md
     *
     * @return the value of article_body.content_md
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    public String getContentMd() {
        return contentMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_body.content_md
     *
     * @param contentMd the value for article_body.content_md
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    public void setContentMd(String contentMd) {
        this.contentMd = contentMd;
    }
}