package cn.gmwenterprise.presevere.domain;

import java.time.LocalDateTime;

public class ArticleMetadata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_metadata.id
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_metadata.url_number
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    private Long urlNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_metadata.title
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_metadata.introduction
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_metadata.tags
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_metadata.writer
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    private Integer writer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_metadata.published_time
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    private LocalDateTime publishedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_metadata.id
     *
     * @return the value of article_metadata.id
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_metadata.id
     *
     * @param id the value for article_metadata.id
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_metadata.url_number
     *
     * @return the value of article_metadata.url_number
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public Long getUrlNumber() {
        return urlNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_metadata.url_number
     *
     * @param urlNumber the value for article_metadata.url_number
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public void setUrlNumber(Long urlNumber) {
        this.urlNumber = urlNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_metadata.title
     *
     * @return the value of article_metadata.title
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_metadata.title
     *
     * @param title the value for article_metadata.title
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_metadata.introduction
     *
     * @return the value of article_metadata.introduction
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_metadata.introduction
     *
     * @param introduction the value for article_metadata.introduction
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_metadata.tags
     *
     * @return the value of article_metadata.tags
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_metadata.tags
     *
     * @param tags the value for article_metadata.tags
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_metadata.writer
     *
     * @return the value of article_metadata.writer
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public Integer getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_metadata.writer
     *
     * @param writer the value for article_metadata.writer
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public void setWriter(Integer writer) {
        this.writer = writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_metadata.published_time
     *
     * @return the value of article_metadata.published_time
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public LocalDateTime getPublishedTime() {
        return publishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_metadata.published_time
     *
     * @param publishedTime the value for article_metadata.published_time
     *
     * @mbg.generated Mon Nov 18 11:38:29 CST 2019
     */
    public void setPublishedTime(LocalDateTime publishedTime) {
        this.publishedTime = publishedTime;
    }
}