package cn.gmwenterprise.presevere.domain;

public class ArticleSubscriber {
    public static final Byte SUBSCRIBER_ON = 1;
    public static final Byte SUBSCRIBER_OFF = 2;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_subscriber.email
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_subscriber.prefix
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    private String prefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_subscriber.suffix
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_subscriber.subscribe
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    private Byte subscribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_subscriber.email
     *
     * @return the value of article_subscriber.email
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_subscriber.email
     *
     * @param email the value for article_subscriber.email
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_subscriber.prefix
     *
     * @return the value of article_subscriber.prefix
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_subscriber.prefix
     *
     * @param prefix the value for article_subscriber.prefix
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_subscriber.suffix
     *
     * @return the value of article_subscriber.suffix
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_subscriber.suffix
     *
     * @param suffix the value for article_subscriber.suffix
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_subscriber.subscribe
     *
     * @return the value of article_subscriber.subscribe
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public Byte getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_subscriber.subscribe
     *
     * @param subscribe the value for article_subscriber.subscribe
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    public void setSubscribe(Byte subscribe) {
        this.subscribe = subscribe;
    }
}