# 基本配置
server:
  port: 4399

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://120.79.155.125:3306/db_presevere_new?serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/
    check-template-location: on
    check-template: false

mybatis:
  type-aliases-package: cn.gmwenterprise.presevere.domain
  mapper-locations: classpath:mapping/**
  configuration:
    cache-enabled: on

logging:
  level:
    cn.gmwenterprise.presevere.dao: DEBUG