package cn.gmwenterprise.presevere.domain;

public class ArticleTagStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag_store.id
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag_store.url_number
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    private Long urlNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag_store.tag
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag_store.id
     *
     * @return the value of article_tag_store.id
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag_store.id
     *
     * @param id the value for article_tag_store.id
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag_store.url_number
     *
     * @return the value of article_tag_store.url_number
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    public Long getUrlNumber() {
        return urlNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag_store.url_number
     *
     * @param urlNumber the value for article_tag_store.url_number
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    public void setUrlNumber(Long urlNumber) {
        this.urlNumber = urlNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag_store.tag
     *
     * @return the value of article_tag_store.tag
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag_store.tag
     *
     * @param tag the value for article_tag_store.tag
     *
     * @mbg.generated Mon Dec 09 15:16:22 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}