package cn.gmwenterprise.presevere.domain;

import org.springframework.util.StringUtils;

public class ArticleDraftWithBLOBs extends ArticleDraft {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_draft.content
     *
     * @mbg.generated Mon Dec 02 11:24:36 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_draft.render_html
     *
     * @mbg.generated Mon Dec 02 11:24:36 CST 2019
     */
    private String renderHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_draft.content
     *
     * @return the value of article_draft.content
     *
     * @mbg.generated Mon Dec 02 11:24:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_draft.content
     *
     * @param content the value for article_draft.content
     *
     * @mbg.generated Mon Dec 02 11:24:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_draft.render_html
     *
     * @return the value of article_draft.render_html
     *
     * @mbg.generated Mon Dec 02 11:24:36 CST 2019
     */
    public String getRenderHtml() {
        return renderHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_draft.render_html
     *
     * @param renderHtml the value for article_draft.render_html
     *
     * @mbg.generated Mon Dec 02 11:24:36 CST 2019
     */
    public void setRenderHtml(String renderHtml) {
        this.renderHtml = renderHtml;
    }

    public void setContentIfNotNull(String markdown) {
        if (!StringUtils.isEmpty(markdown)) {
            setContent(markdown);
        }
    }

    public void setRenderHtmlIfNotNull(String render) {
        if (!StringUtils.isEmpty(render)) {
            setRenderHtml(render);
        }
    }
}