spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-data-in-action?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver