server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GmwEnterprise/presevere/
          search-paths: demo/cloud-parent/config-repo
          username: GmwEnterprise
          password: gan1ming2wei3