server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://gitee.com/mrag/demo-cloud-config-repo/
          search-paths: licensingservice
          username: mrag
          password: gan1ming2wei3