package cn.gmwenterprise.presevere.dao;

import cn.gmwenterprise.presevere.domain.ArticleBody;
import cn.gmwenterprise.presevere.domain.ArticleBodyWithBLOBs;

import java.util.List;

public interface ArticleBodyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_body
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_body
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    int insert(ArticleBodyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_body
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    int insertSelective(ArticleBodyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_body
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    ArticleBodyWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_body
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleBodyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_body
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ArticleBodyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_body
     *
     * @mbg.generated Mon Dec 09 11:27:56 CST 2019
     */
    int updateByPrimaryKey(ArticleBody record);

    int updateByUrlNumberWithBLOBs(ArticleBodyWithBLOBs body);

    ArticleBodyWithBLOBs selectByUrlNumber(Long url);

    List<ArticleBodyWithBLOBs> selective(ArticleBody record);
}