package cn.gmwenterprise.presevere.dao;

import cn.gmwenterprise.presevere.domain.ArticleSubscriber;

import java.util.List;

public interface ArticleSubscriberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_subscriber
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    int insert(ArticleSubscriber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_subscriber
     *
     * @mbg.generated Thu Dec 12 15:22:33 CST 2019
     */
    int insertSelective(ArticleSubscriber record);

    List<ArticleSubscriber> selectAll(Byte subscribe);

    int updateSubscriberByEmail(ArticleSubscriber record);

    ArticleSubscriber selectByEmail(String email);
}